using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace LitleHelperServer;

public class Branch
{
    public int Id { get; set; }
    public string Name { get; set; } = "";
    public bool IsActive { get; set; } = true;
}
public static class Branches
{
    public static bool CanHandle(PanelUser user, TicketRecord ticket) => user.Role == Roles.SuperAdmin || ticket.BranchId == null || user.BranchId == ticket.BranchId;
    public static void Require(PanelUser user, TicketRecord ticket)
    { if (!CanHandle(user, ticket)) throw new UnauthorizedAccessException("Заявка относится к другому филиалу. Проверьте филиал в профиле пользователя."); }
    public static async Task ValidateUserAsync(HelperDb db, int? id)
    { if (id != null && !await db.Branches.AnyAsync(b => b.Id == id)) throw new ArgumentException("Выберите действующий филиал."); }
    public static async Task<Branch?> ValidateTicketAsync(HelperDb db, int? id, string room)
    {
        if (room.Length > 100 || room.Any(char.IsControl)) throw new ArgumentException("Кабинет: до 100 символов без переносов строк.");
        if (id == null)
        {
            if (await db.Branches.AnyAsync(b => b.IsActive)) throw new ArgumentException("Выберите филиал и укажите кабинет. Обновите клиент, если этих полей нет.");
            return null;
        }
        var branch = await db.Branches.SingleOrDefaultAsync(b => b.Id == id && b.IsActive) ?? throw new ArgumentException("Филиал недоступен. Обновите список филиалов.");
        if (string.IsNullOrWhiteSpace(room)) throw new ArgumentException("Укажите кабинет.");
        return branch;
    }
    public static string Description(string text, Branch? branch, string room) => branch == null ? text : "Филиал: " + branch.Name + "\nКабинет: " + room.Trim() + "\n\n" + text;
    public static async Task EnsureSchemaAsync(HelperDb db)
    {
        bool pg = db.Database.IsNpgsql();
        string key = pg ? "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" : "INTEGER PRIMARY KEY AUTOINCREMENT";
        await db.Database.ExecuteSqlRawAsync("CREATE TABLE IF NOT EXISTS \"Branches\" (\"Id\" " + key + ", \"Name\" TEXT NOT NULL, \"IsActive\" " + (pg ? "BOOLEAN" : "INTEGER") + " NOT NULL)");
        foreach (var (table, column, type) in new[] { ("Users", "BranchId", "INTEGER NULL"), ("Tickets", "BranchId", "INTEGER NULL"), ("Tickets", "BranchName", "TEXT NOT NULL DEFAULT ''"), ("Tickets", "Room", "TEXT NOT NULL DEFAULT ''") })
        {
            if (pg) await db.Database.ExecuteSqlRawAsync("ALTER TABLE \"" + table + "\" ADD COLUMN IF NOT EXISTS \"" + column + "\" " + type);
            else
            {
                await db.Database.OpenConnectionAsync(); using var cmd = db.Database.GetDbConnection().CreateCommand(); cmd.CommandText = $"PRAGMA table_info('{table}')";
                bool found = false; using (var reader = await cmd.ExecuteReaderAsync()) while (await reader.ReadAsync()) if (reader.GetString(1) == column) found = true;
                if (!found) await db.Database.ExecuteSqlRawAsync("ALTER TABLE \"" + table + "\" ADD COLUMN \"" + column + "\" " + type);
                await db.Database.CloseConnectionAsync();
            }
        }
    }
    public static void MapBranchApi(this WebApplication app)
    {
        app.MapGet("/api/branches", async (HelperDb db) => Results.Ok(await db.Branches.AsNoTracking().OrderBy(b => b.Name).ToListAsync())).RequireAuthorization("Panel");
        app.MapPost("/api/branches", async (Branch branch, HelperDb db) =>
        { await ValidateAsync(branch, db); branch.Id = 0; db.Branches.Add(branch); await db.SaveChangesAsync(); return Results.Ok(branch); }).RequireAuthorization("settings.manage");
        app.MapPut("/api/branches/{id:int}", async (int id, Branch input, HelperDb db) =>
        { input.Id = id; await ValidateAsync(input, db); var branch = await db.Branches.FindAsync(id); if (branch == null) return Results.NotFound(); branch.Name = input.Name; branch.IsActive = input.IsActive; await db.SaveChangesAsync(); return Results.Ok(branch); }).RequireAuthorization("settings.manage");
        app.MapDelete("/api/branches/{id:int}", async (int id, HelperDb db) =>
        {
            var branch = await db.Branches.FindAsync(id); if (branch == null) return Results.NotFound();
            if (await db.Users.AnyAsync(u => u.BranchId == id) || await db.Tickets.AnyAsync(t => t.BranchId == id)) return Results.Conflict(new { error = "Филиал используется в пользователях или заявках. Отключите его, чтобы сохранить историю." });
            db.Branches.Remove(branch); await db.SaveChangesAsync(); return Results.NoContent();
        }).RequireAuthorization("settings.manage");
    }
    private static async Task ValidateAsync(Branch branch, HelperDb db)
    {
        branch.Name = branch.Name.Trim();
        if (branch.Name.Length is < 1 or > 100 || branch.Name.Any(char.IsControl)) throw new ArgumentException("Название филиала: от 1 до 100 символов.");
        if (await db.Branches.AnyAsync(b => b.Id != branch.Id && b.Name.ToLower() == branch.Name.ToLower())) throw new ArgumentException("Филиал с таким названием уже существует.");
    }
}
