using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace LitleHelperServer;

public class ChatGroup
{
    public int Id { get; set; }
    public string Name { get; set; } = "";
    public int OwnerId { get; set; }
    public bool IsClosed { get; set; }
}
public class ChatGroupMember
{
    public int GroupId { get; set; }
    public int UserId { get; set; }
    public long JoinedAfterId { get; set; }
    public long ReadThroughId { get; set; }
}
public class ChatGroupMessage
{
    public long Id { get; set; }
    public int GroupId { get; set; }
    public int SenderId { get; set; }
    public string Body { get; set; } = "";
    public string ClientId { get; set; } = "";
    public DateTime SentAt { get; set; } = DateTime.UtcNow;
}
public record ChatListItem(int Id, string FullName, string Username, bool IsActive, string? Branch, int Unread, long? LastId,
    bool IsOnline, DateTime? LastAt, string? LastText, bool IsGroup = false, int? OwnerId = null);
public record GroupCreate(string Name, int[] Members);
public record GroupUpdate(string Name);
public record GroupUser(int UserId);
// Membership changes and sends use one gate, including across await boundaries.
// The deployment runs one server instance; scale-out requires a distributed gate.
public class ChatGroupGate { public SemaphoreSlim Semaphore { get; } = new(1, 1); }
public static class ChatGroups
{
    public static int IdFromPeer(int peer) => peer < 0 && peer != int.MinValue ? -peer : throw new ArgumentException("Некорректная группа.");
    public static async Task EnsureSchemaAsync(HelperDb db)
    {
        bool pg = db.Database.IsNpgsql(); string identity = pg ? "INTEGER GENERATED BY DEFAULT AS IDENTITY" : "INTEGER";
        string longIdentity = pg ? "BIGINT GENERATED BY DEFAULT AS IDENTITY" : "INTEGER", date = pg ? "timestamp with time zone" : "TEXT", boolean = pg ? "boolean" : "INTEGER";
        string groupsSql = $"CREATE TABLE IF NOT EXISTS \"ChatGroups\" (\"Id\" {identity} PRIMARY KEY, \"Name\" TEXT NOT NULL, \"OwnerId\" INTEGER NOT NULL REFERENCES \"Users\"(\"Id\"), \"IsClosed\" {boolean} NOT NULL)";
        await db.Database.ExecuteSqlRawAsync(groupsSql); // Only fixed provider-specific type literals are interpolated.
        await db.Database.ExecuteSqlRawAsync("CREATE TABLE IF NOT EXISTS \"ChatGroupMembers\" (\"GroupId\" INTEGER NOT NULL REFERENCES \"ChatGroups\"(\"Id\"), \"UserId\" INTEGER NOT NULL REFERENCES \"Users\"(\"Id\"), \"JoinedAfterId\" BIGINT NOT NULL, \"ReadThroughId\" BIGINT NOT NULL, PRIMARY KEY (\"GroupId\", \"UserId\"))");
        string messagesSql = $"CREATE TABLE IF NOT EXISTS \"ChatGroupMessages\" (\"Id\" {longIdentity} PRIMARY KEY{(pg ? "" : " AUTOINCREMENT")}, \"GroupId\" INTEGER NOT NULL REFERENCES \"ChatGroups\"(\"Id\"), \"SenderId\" INTEGER NOT NULL REFERENCES \"Users\"(\"Id\"), \"Body\" TEXT NOT NULL, \"ClientId\" TEXT NOT NULL, \"SentAt\" {date} NOT NULL)";
        await db.Database.ExecuteSqlRawAsync(messagesSql);
        await db.Database.ExecuteSqlRawAsync("CREATE UNIQUE INDEX IF NOT EXISTS \"IX_ChatGroupMessages_SenderId_ClientId\" ON \"ChatGroupMessages\" (\"SenderId\", \"ClientId\")");
        await db.Database.ExecuteSqlRawAsync("CREATE INDEX IF NOT EXISTS \"IX_ChatGroupMessages_GroupId_Id\" ON \"ChatGroupMessages\" (\"GroupId\", \"Id\")");
        await db.Database.ExecuteSqlRawAsync("CREATE INDEX IF NOT EXISTS \"IX_ChatGroupMembers_UserId\" ON \"ChatGroupMembers\" (\"UserId\")");
    }
    private static string Name(string value) => !string.IsNullOrWhiteSpace(value) && value.Trim().Length <= 80 && !value.Any(char.IsControl) ? value.Trim() : throw new ArgumentException("Название группы: от 1 до 80 символов.");
    private static async Task<ChatGroupMember> Member(HelperDb db, int group, int user) => await db.ChatGroupMembers.SingleOrDefaultAsync(m => m.GroupId == group && m.UserId == user) ?? throw new UnauthorizedAccessException("Вы не состоите в этой группе.");
    private static async Task<ChatGroup> Owner(HelperDb db, int group, int user)
    {
        await Member(db, group, user);
        var item = await db.ChatGroups.SingleAsync(g => g.Id == group);
        if (item.OwnerId != user) throw new UnauthorizedAccessException("Управлять группой может только её создатель.");
        return item;
    }
    private static ChatMessage View(ChatGroupMessage message, long readThrough, string sender) => new() { Id = message.Id, SenderId = message.SenderId, RecipientId = -message.GroupId, Body = message.Body, ClientId = message.ClientId, SentAt = message.SentAt, SenderName = sender, ReadAt = message.Id <= readThrough ? message.SentAt : null };
    public static async Task<List<ChatListItem>> ListAsync(HelperDb db, int user)
    {
        var memberships = await db.ChatGroupMembers.AsNoTracking().Where(m => m.UserId == user).ToListAsync(); var list = new List<ChatListItem>();
        foreach (var member in memberships)
        {
            var group = await db.ChatGroups.AsNoTracking().SingleAsync(g => g.Id == member.GroupId);
            var visible = db.ChatGroupMessages.AsNoTracking().Where(m => m.GroupId == group.Id && m.Id > member.JoinedAfterId);
            var last = await visible.OrderByDescending(m => m.Id).FirstOrDefaultAsync();
            int unread = await visible.CountAsync(m => m.Id > member.ReadThroughId && m.SenderId != user);
            list.Add(new(-group.Id, group.Name, "", !group.IsClosed, null, unread, last?.Id, false, last?.SentAt, last?.Body, true, group.OwnerId));
        }
        return list;
    }
    public static async Task<IResult> HistoryAsync(int group, long? before, HelperDb db, int user)
    {
        var member = await Member(db, group, user);
        var rows = await db.ChatGroupMessages.AsNoTracking().Where(m => m.GroupId == group && m.Id > member.JoinedAfterId && (before == null || m.Id < before)).OrderByDescending(m => m.Id).Take(50).ToListAsync();
        var names = await db.Users.Where(u => rows.Select(m => m.SenderId).Contains(u.Id)).ToDictionaryAsync(u => u.Id, u => u.FullName);
        return Results.Ok(rows.OrderBy(m => m.Id).Select(m => View(m, member.ReadThroughId, names[m.SenderId])));
    }
    public static async Task<IResult> SendAsync(ChatSend request, HelperDb db, int user, IHubContext<MessengerHub> hub, ChatGroupGate gate)
    {
        if (request.RecipientId == int.MinValue || !Guid.TryParse(request.ClientId, out _) || string.IsNullOrWhiteSpace(request.Body) || request.Body.Length > 4000 || request.Body.Any(c => char.IsControl(c) && c is not '\n' and not '\r' and not '\t')) throw new ArgumentException("Некорректное сообщение.");
        int group = -request.RecipientId; string clientId = Guid.Parse(request.ClientId).ToString("N");
        await gate.Semaphore.WaitAsync();
        try
        {
            await Member(db, group, user);
            if ((await db.ChatGroups.SingleAsync(g => g.Id == group)).IsClosed) throw new ArgumentException("Группа закрыта. История доступна для чтения.");
            var old = await db.ChatGroupMessages.SingleOrDefaultAsync(m => m.SenderId == user && m.ClientId == clientId);
            if (old != null)
            { if (old.GroupId != group || old.Body != request.Body.Trim()) throw new ArgumentException("Идентификатор сообщения уже использован."); return Results.Ok(View(old, 0, (await db.Users.FindAsync(user))!.FullName)); }
            var message = new ChatGroupMessage { GroupId = group, SenderId = user, Body = request.Body.Trim(), ClientId = clientId }; db.ChatGroupMessages.Add(message); await db.SaveChangesAsync();
            var recipients = await db.ChatGroupMembers.Where(m => m.GroupId == group && db.Users.Any(u => u.Id == m.UserId && u.IsActive)).Select(m => "Chat:" + m.UserId).ToArrayAsync();
            var result = View(message, 0, (await db.Users.FindAsync(user))!.FullName);
            await hub.Clients.Groups(recipients).SendAsync("ChatMessage", result); return Results.Ok(result);
        }
        finally { gate.Semaphore.Release(); }
    }
    public static async Task<IResult> ReadAsync(int group, long through, HelperDb db, int user, IHubContext<MessengerHub> hub)
    {
        var member = await Member(db, group, user);
        long maximum = await db.ChatGroupMessages.Where(m => m.GroupId == group && m.Id <= through && m.Id > member.JoinedAfterId).Select(m => (long?)m.Id).MaxAsync() ?? member.JoinedAfterId;
        await db.ChatGroupMembers.Where(m => m.GroupId == group && m.UserId == user && m.ReadThroughId < maximum).ExecuteUpdateAsync(s => s.SetProperty(m => m.ReadThroughId, maximum));
        await hub.Clients.Group("Chat:" + user).SendAsync("ChatChanged"); return Results.Ok();
    }
    private static async Task Changed(HelperDb db, int group, IHubContext<MessengerHub> hub, int? extra = null)
    {
        var ids = await db.ChatGroupMembers.Where(m => m.GroupId == group).Select(m => m.UserId).ToListAsync(); if (extra != null) ids.Add(extra.Value);
        await hub.Clients.Groups(ids.Distinct().Select(id => "Chat:" + id)).SendAsync("ChatChanged");
    }
    public static void Map(RouteGroupBuilder api)
    {
        api.MapPost("/groups", async (GroupCreate request, HelperDb db, ClaimsPrincipal p, ChatGroupGate gate, IHubContext<MessengerHub> hub) =>
        {
            var me = await Messenger.UserAsync(db, p); string name = Name(request.Name); int[] ids = (request.Members ?? []).Append(me.Id).Distinct().ToArray();
            if (ids.Length is < 2 or > 100) throw new ArgumentException("Группа: от 2 до 100 участников.");
            await gate.Semaphore.WaitAsync();
            try
            {
                if (await db.Users.CountAsync(u => ids.Contains(u.Id) && u.IsActive && u.PasswordHash == "!AD") != ids.Length) throw new ArgumentException("Один из участников недоступен.");
                await using var transaction = await db.Database.BeginTransactionAsync();
                var group = new ChatGroup { Name = name, OwnerId = me.Id }; db.ChatGroups.Add(group); await db.SaveChangesAsync();
                db.ChatGroupMembers.AddRange(ids.Select(id => new ChatGroupMember { GroupId = group.Id, UserId = id })); await db.SaveChangesAsync(); await transaction.CommitAsync();
                await Changed(db, group.Id, hub); return Results.Ok(new { id = -group.Id });
            }
            finally { gate.Semaphore.Release(); }
        });
        api.MapGet("/groups/{group:int}", async (int group, HelperDb db, ClaimsPrincipal p) =>
        {
            var me = await Messenger.UserAsync(db, p); await Member(db, group, me.Id); var item = await db.ChatGroups.SingleAsync(g => g.Id == group);
            var members = await db.ChatGroupMembers.Where(m => m.GroupId == group).Join(db.Users, m => m.UserId, u => u.Id, (m, u) => new { u.Id, u.FullName, u.Username, u.IsActive }).ToListAsync();
            return Results.Ok(new { item.Id, item.Name, item.OwnerId, item.IsClosed, members });
        });
        api.MapPost("/groups/{group:int}/{operation}", async (int group, string operation, HttpRequest http, HelperDb db, ClaimsPrincipal p, ChatGroupGate gate, IHubContext<MessengerHub> hub) =>
        {
            var me = await Messenger.UserAsync(db, p); await gate.Semaphore.WaitAsync();
            try
            {
                var membership = await Member(db, group, me.Id); var item = await db.ChatGroups.SingleAsync(g => g.Id == group); int? removed = null;
                if (operation == "leave")
                {
                    if (item.OwnerId == me.Id && await db.ChatGroupMembers.CountAsync(m => m.GroupId == group) > 1) throw new ArgumentException("Передайте владение группой другому участнику перед выходом.");
                    if (item.OwnerId == me.Id) item.IsClosed = true;
                    db.ChatGroupMembers.Remove(membership); removed = me.Id;
                }
                else
                {
                    item = await Owner(db, group, me.Id);
                    if (operation == "close") item.IsClosed = true;
                    else
                    {
                        if (item.IsClosed) throw new ArgumentException("Группа закрыта.");
                        if (operation == "rename") { var request = await http.ReadFromJsonAsync<GroupUpdate>() ?? throw new ArgumentException(); item.Name = Name(request.Name); }
                        else if (operation is "invite" or "remove" or "owner")
                        {
                            int id = (await http.ReadFromJsonAsync<GroupUser>() ?? throw new ArgumentException()).UserId;
                            var member = await db.ChatGroupMembers.SingleOrDefaultAsync(m => m.GroupId == group && m.UserId == id);
                            if (operation == "invite")
                            {
                                if (!await db.Users.AnyAsync(u => u.Id == id && u.IsActive && u.PasswordHash == "!AD")) throw new ArgumentException("Участник недоступен.");
                                if (member == null)
                                {
                                    if (await db.ChatGroupMembers.CountAsync(m => m.GroupId == group) >= 100) throw new ArgumentException("Не больше 100 участников.");
                                    long maximum = await db.ChatGroupMessages.Where(m => m.GroupId == group).Select(m => (long?)m.Id).MaxAsync() ?? 0;
                                    db.ChatGroupMembers.Add(new() { GroupId = group, UserId = id, JoinedAfterId = maximum, ReadThroughId = maximum });
                                }
                            }
                            else
                            {
                                if (member == null || id == me.Id) throw new ArgumentException("Выберите другого участника.");
                                if (operation == "owner") { if (!await db.Users.AnyAsync(u => u.Id == id && u.IsActive)) throw new ArgumentException("Участник отключён."); item.OwnerId = id; }
                                else { db.ChatGroupMembers.Remove(member); removed = id; }
                            }
                        }
                        else throw new ArgumentException("Неизвестная операция.");
                    }
                }
                await db.SaveChangesAsync(); await Changed(db, group, hub, removed); return Results.Ok();
            }
            finally { gate.Semaphore.Release(); }
        });
    }
}
