using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace LitleHelperServer;

public class ChatGroup
{
    public int Id { get; set; }
    public string Name { get; set; } = "";
    public int OwnerId { get; set; }
    public bool IsClosed { get; set; }
    public bool IsDeleted { get; set; }
}
public class ChatGroupMember
{
    public int GroupId { get; set; }
    public int UserId { get; set; }
    public long JoinedAfterId { get; set; }
    public long ReadThroughId { get; set; }
    public bool IsAdmin { get; set; }
    public DateTime JoinedAt { get; set; } = DateTime.UtcNow;
}
public class ChatGroupDeparture
{
    public int GroupId { get; set; }
    public int UserId { get; set; }
    public long JoinedAfterId { get; set; }
    public long ReadThroughId { get; set; }
    public DateTime JoinedAt { get; set; }
    public DateTime LeftAt { get; set; }
}
public class ChatGroupMessage
{
    public bool IsUrgent { get; set; }
    public string? Command { get; set; }
    public long Id { get; set; }
    public int GroupId { get; set; }
    public int SenderId { get; set; }
    public string Body { get; set; } = "";
    public string ClientId { get; set; } = "";
    public DateTime SentAt { get; set; } = DateTime.UtcNow;
}
public record ChatListItem(int Id, string FullName, string Username, bool IsActive, string? Branch, int Unread, long? LastId,
    bool IsOnline, DateTime? LastAt, string? LastText, bool IsGroup = false, int? OwnerId = null, DateTime? SuspendedUntil = null, bool IsAdmin = false);
public class ChatGroupEvent
{
    public string Id { get; set; } = Guid.NewGuid().ToString("N");
    public int GroupId { get; set; }
    public long AfterMessageId { get; set; }
    public DateTime SentAt { get; set; } = DateTime.UtcNow;
    public string Body { get; set; } = "";
}
public record GroupCreate(string Name, int[] Members);
public record GroupUpdate(string Name);
public record GroupUser(int UserId);
public record GroupSuspend(int UserId, int Minutes);
public class ChatGroupRestriction
{
    public string Id { get; set; } = Guid.NewGuid().ToString("N");
    public int GroupId { get; set; }
    public int UserId { get; set; }
    public DateTime StartedAt { get; set; } = DateTime.UtcNow;
    public DateTime EndsAt { get; set; }
}
// Membership changes and sends use one gate, including across await boundaries.
// The deployment runs one server instance; scale-out requires a distributed gate.
public class ChatGroupGate { public SemaphoreSlim Semaphore { get; } = new(1, 1); }
public static class ChatGroups
{
    public static int IdFromPeer(int peer) => peer < 0 && peer != int.MinValue ? -peer : throw new ArgumentException("Некорректная группа.");
    public static async Task EnsureSchemaAsync(HelperDb db)
    {
        bool pg = db.Database.IsNpgsql(); string identity = pg ? "INTEGER GENERATED BY DEFAULT AS IDENTITY" : "INTEGER";
        string longIdentity = pg ? "BIGINT GENERATED BY DEFAULT AS IDENTITY" : "INTEGER", date = pg ? "timestamp with time zone" : "TEXT", boolean = pg ? "boolean" : "INTEGER";
        string groupsSql = $"CREATE TABLE IF NOT EXISTS \"ChatGroups\" (\"Id\" {identity} PRIMARY KEY, \"Name\" TEXT NOT NULL, \"OwnerId\" INTEGER NOT NULL REFERENCES \"Users\"(\"Id\"), \"IsClosed\" {boolean} NOT NULL)";
        await db.Database.ExecuteSqlRawAsync(groupsSql); // Only fixed provider-specific type literals are interpolated.
        await db.Database.ExecuteSqlRawAsync("CREATE TABLE IF NOT EXISTS \"ChatGroupMembers\" (\"GroupId\" INTEGER NOT NULL REFERENCES \"ChatGroups\"(\"Id\"), \"UserId\" INTEGER NOT NULL REFERENCES \"Users\"(\"Id\"), \"JoinedAfterId\" BIGINT NOT NULL, \"ReadThroughId\" BIGINT NOT NULL, PRIMARY KEY (\"GroupId\", \"UserId\"))");
        string messagesSql = $"CREATE TABLE IF NOT EXISTS \"ChatGroupMessages\" (\"Id\" {longIdentity} PRIMARY KEY{(pg ? "" : " AUTOINCREMENT")}, \"GroupId\" INTEGER NOT NULL REFERENCES \"ChatGroups\"(\"Id\"), \"SenderId\" INTEGER NOT NULL REFERENCES \"Users\"(\"Id\"), \"Body\" TEXT NOT NULL, \"ClientId\" TEXT NOT NULL, \"SentAt\" {date} NOT NULL)";
        await db.Database.ExecuteSqlRawAsync(messagesSql);
        await db.Database.ExecuteSqlRawAsync("CREATE UNIQUE INDEX IF NOT EXISTS \"IX_ChatGroupMessages_SenderId_ClientId\" ON \"ChatGroupMessages\" (\"SenderId\", \"ClientId\")");
        await db.Database.ExecuteSqlRawAsync("CREATE INDEX IF NOT EXISTS \"IX_ChatGroupMessages_GroupId_Id\" ON \"ChatGroupMessages\" (\"GroupId\", \"Id\")");
        await db.Database.ExecuteSqlRawAsync("CREATE INDEX IF NOT EXISTS \"IX_ChatGroupMembers_UserId\" ON \"ChatGroupMembers\" (\"UserId\")");
        string restrictionSql = $"CREATE TABLE IF NOT EXISTS \"ChatGroupRestrictions\" (\"Id\" TEXT PRIMARY KEY, \"GroupId\" INTEGER NOT NULL, \"UserId\" INTEGER NOT NULL, \"StartedAt\" {date} NOT NULL, \"EndsAt\" {date} NOT NULL)";
        await db.Database.ExecuteSqlRawAsync(restrictionSql);
        await ChatBroadcasts.Column(db, "ChatGroups", "IsDeleted", boolean + " NOT NULL DEFAULT " + (pg ? "false" : "0"));
        await ChatBroadcasts.Column(db, "ChatGroupMembers", "IsAdmin", boolean + " NOT NULL DEFAULT " + (pg ? "false" : "0"));
        await ChatBroadcasts.Column(db, "ChatGroupMembers", "JoinedAt", date + " NOT NULL DEFAULT '1970-01-01T00:00:00Z'");
        string departuresSql = $"CREATE TABLE IF NOT EXISTS \"ChatGroupDepartures\" (\"GroupId\" INTEGER NOT NULL, \"UserId\" INTEGER NOT NULL, \"JoinedAfterId\" BIGINT NOT NULL, \"ReadThroughId\" BIGINT NOT NULL, \"JoinedAt\" {date} NOT NULL, \"LeftAt\" {date} NOT NULL, PRIMARY KEY (\"GroupId\", \"UserId\"))";
        await db.Database.ExecuteSqlRawAsync(departuresSql);
        string eventsSql = $"CREATE TABLE IF NOT EXISTS \"ChatGroupEvents\" (\"Id\" TEXT PRIMARY KEY, \"GroupId\" INTEGER NOT NULL, \"AfterMessageId\" BIGINT NOT NULL, \"SentAt\" {date} NOT NULL, \"Body\" TEXT NOT NULL)";
        await db.Database.ExecuteSqlRawAsync(eventsSql);
        await db.Database.ExecuteSqlRawAsync("CREATE INDEX IF NOT EXISTS \"IX_ChatGroupEvents_GroupId_SentAt\" ON \"ChatGroupEvents\" (\"GroupId\", \"SentAt\")");
    }
    private static string Name(string value) => !string.IsNullOrWhiteSpace(value) && value.Trim().Length <= 80 && !value.Any(char.IsControl) ? value.Trim() : throw new ArgumentException("Название группы: от 1 до 80 символов.");
    public static async Task<ChatGroupMember> Member(HelperDb db, int group, int user)
    {
        if (!await db.ChatGroups.AnyAsync(g => g.Id == group && !g.IsDeleted)) throw new UnauthorizedAccessException("Группа удалена или недоступна.");
        var member = await db.ChatGroupMembers.SingleOrDefaultAsync(m => m.GroupId == group && m.UserId == user) ?? throw new UnauthorizedAccessException("Вы не состоите в этой группе.");
        if (await db.ChatGroupRestrictions.AnyAsync(r => r.GroupId == group && r.UserId == user && r.EndsAt > DateTime.UtcNow)) throw new UnauthorizedAccessException("Доступ к группе временно отключён.");
        return member;
    }
    internal static IQueryable<ChatGroupMessage> Visible(HelperDb db, ChatGroupMember member) => db.ChatGroupMessages.AsNoTracking().Where(m => m.GroupId == member.GroupId && m.Id > member.JoinedAfterId && !db.ChatGroupRestrictions.Any(r => r.GroupId == m.GroupId && r.UserId == member.UserId && m.SentAt >= r.StartedAt && m.SentAt < r.EndsAt));
    private static ChatMessage View(ChatGroupMessage message, long readThrough, string sender) => new() { Id = message.Id, SenderId = message.SenderId, RecipientId = -message.GroupId, Body = message.Body, IsUrgent = message.IsUrgent, Command = message.Command, ClientId = message.ClientId, SentAt = message.SentAt, SenderName = sender, ReadAt = message.Id <= readThrough ? message.SentAt : null };
    public static async Task<List<ChatListItem>> ListAsync(HelperDb db, int user)
    {
        var memberships = await db.ChatGroupMembers.AsNoTracking().Where(m => m.UserId == user).ToListAsync(); var list = new List<ChatListItem>();
        foreach (var member in memberships)
        {
            var group = await db.ChatGroups.AsNoTracking().SingleAsync(g => g.Id == member.GroupId);
            if (group.IsDeleted) continue;
            var visible = Visible(db, member);
            var suspendedUntil = await db.ChatGroupRestrictions.Where(r => r.GroupId == group.Id && r.UserId == user && r.EndsAt > DateTime.UtcNow).Select(r => (DateTime?)r.EndsAt).MaxAsync(); bool suspended = suspendedUntil != null;
            var last = await visible.OrderByDescending(m => m.Id).FirstOrDefaultAsync();
            int unread = await visible.CountAsync(m => m.Id > member.ReadThroughId && m.SenderId != user && m.Body != "");
            list.Add(new(-group.Id, group.Name, "", !group.IsClosed && !suspended, null, suspended ? 0 : unread, last?.Id, false, last?.SentAt, last?.Body, true, group.OwnerId, suspendedUntil, member.IsAdmin));
        }
        return list;
    }
    public static async Task<IResult> HistoryAsync(int group, long? before, HelperDb db, int user)
    {
        var member = await Member(db, group, user);
        var rows = await Visible(db, member).Where(m => before == null || m.Id < before).OrderByDescending(m => m.Id).Take(50).ToListAsync();
        var names = await db.Users.Where(u => rows.Select(m => m.SenderId).Contains(u.Id)).ToDictionaryAsync(u => u.Id, u => u.FullName);
        var result = rows.OrderBy(m => m.Id).Select(m => View(m, member.ReadThroughId, names[m.SenderId])).ToList();
        await ChatFiles.PopulateAsync(db, result); return Results.Ok(result);
    }
    public static async Task<IResult> SendAsync(ChatSend request, HelperDb db, int user, IHubContext<MessengerHub> hub, ChatGroupGate gate)
    {
        if (request.RecipientId == int.MinValue || !Guid.TryParse(request.ClientId, out _) || string.IsNullOrWhiteSpace(request.Body) || request.Body.Length > 4000 || request.Body.Any(c => char.IsControl(c) && c is not '\n' and not '\r' and not '\t')) throw new ArgumentException("Некорректное сообщение.");
        var content = ChatCommands.Parse(request.Body);
        int group = -request.RecipientId; string clientId = Guid.Parse(request.ClientId).ToString("N");
        await gate.Semaphore.WaitAsync();
        try
        {
            await Member(db, group, user);
            if ((await db.ChatGroups.SingleAsync(g => g.Id == group)).IsClosed) throw new ArgumentException("Группа закрыта. История доступна для чтения.");
            var old = await db.ChatGroupMessages.SingleOrDefaultAsync(m => m.SenderId == user && m.ClientId == clientId);
            if (old != null)
            { if (old.GroupId != group || old.Body != content.Body || old.IsUrgent != content.Urgent || old.Command != content.Command) throw new ArgumentException("Идентификатор сообщения уже использован."); return Results.Ok(View(old, 0, (await db.Users.FindAsync(user))!.FullName)); }
            var message = new ChatGroupMessage { GroupId = group, SenderId = user, Body = content.Body, IsUrgent = content.Urgent, Command = content.Command, ClientId = clientId }; db.ChatGroupMessages.Add(message); await db.SaveChangesAsync();
            var recipients = await db.ChatGroupMembers.Where(m => m.GroupId == group && db.Users.Any(u => u.Id == m.UserId && u.IsActive) && !db.ChatGroupRestrictions.Any(r => r.GroupId == group && r.UserId == m.UserId && r.EndsAt > DateTime.UtcNow)).Select(m => "Chat:" + m.UserId).ToArrayAsync();
            var result = View(message, 0, (await db.Users.FindAsync(user))!.FullName);
            await hub.Clients.Groups(recipients).SendAsync("ChatMessage", result); return Results.Ok(result);
        }
        finally { gate.Semaphore.Release(); }
    }
    public static async Task<IResult> ReadAsync(int group, long through, HelperDb db, int user, IHubContext<MessengerHub> hub)
    {
        var member = await Member(db, group, user);
        long maximum = await Visible(db, member).Where(m => m.Id <= through).Select(m => (long?)m.Id).MaxAsync() ?? member.JoinedAfterId;
        await db.ChatGroupMembers.Where(m => m.GroupId == group && m.UserId == user && m.ReadThroughId < maximum).ExecuteUpdateAsync(s => s.SetProperty(m => m.ReadThroughId, maximum));
        await hub.Clients.Group("Chat:" + user).SendAsync("ChatChanged"); return Results.Ok();
    }
    private static async Task Changed(HelperDb db, int group, IHubContext<MessengerHub> hub, int? extra = null)
    {
        var ids = await db.ChatGroupMembers.Where(m => m.GroupId == group).Select(m => m.UserId).ToListAsync(); if (extra != null) ids.Add(extra.Value);
        await hub.Clients.Groups(ids.Distinct().Select(id => "Chat:" + id)).SendAsync("ChatChanged");
    }
    public static void Map(RouteGroupBuilder api)
    {
        api.MapPost("/groups", async (GroupCreate request, HelperDb db, ClaimsPrincipal p, ChatGroupGate gate, IHubContext<MessengerHub> hub) =>
        {
            var me = await Messenger.UserAsync(db, p); string name = Name(request.Name); int[] ids = (request.Members ?? []).Append(me.Id).Distinct().ToArray();
            if (ids.Length is < 2 or > 100) throw new ArgumentException("Группа: от 2 до 100 участников.");
            await gate.Semaphore.WaitAsync();
            try
            {
                if (await db.Users.CountAsync(u => ids.Contains(u.Id) && u.IsActive && u.PasswordHash == "!AD") != ids.Length) throw new ArgumentException("Один из участников недоступен.");
                await using var transaction = await db.Database.BeginTransactionAsync();
                var group = new ChatGroup { Name = name, OwnerId = me.Id }; db.ChatGroups.Add(group); await db.SaveChangesAsync();
                db.ChatGroupMembers.AddRange(ids.Select(id => new ChatGroupMember { GroupId = group.Id, UserId = id })); await db.SaveChangesAsync(); await transaction.CommitAsync();
                await Changed(db, group.Id, hub); return Results.Ok(new { id = -group.Id });
            }
            finally { gate.Semaphore.Release(); }
        });
        api.MapGet("/groups/{group:int}", async (int group, HelperDb db, ClaimsPrincipal p, ChatPresence presence) =>
        {
            var me = await Messenger.UserAsync(db, p); var membership = await Member(db, group, me.Id); var item = await db.ChatGroups.SingleAsync(g => g.Id == group);
            var rows = await db.ChatGroupMembers.Where(m => m.GroupId == group).Join(db.Users, m => m.UserId, u => u.Id, (m, u) => new { u.Id, u.FullName, u.Username, u.IsActive, m.IsAdmin }).ToListAsync();
            var restrictions = await db.ChatGroupRestrictions.Where(r => r.GroupId == group && r.EndsAt > DateTime.UtcNow).ToListAsync();
            var members = rows.Select(u => new { u.Id, u.FullName, u.Username, u.IsActive, u.IsAdmin, isOwner = u.Id == item.OwnerId, isOnline = presence.Online(u.Id), suspendedUntil = restrictions.Where(r => r.UserId == u.Id).Select(r => (DateTime?)r.EndsAt).Max() });
            var events = await db.ChatGroupEvents.AsNoTracking().Where(e => e.GroupId == group && e.SentAt >= membership.JoinedAt && !db.ChatGroupRestrictions.Any(r => r.GroupId == group && r.UserId == me.Id && e.SentAt >= r.StartedAt && e.SentAt < r.EndsAt)).OrderByDescending(e => e.SentAt).Take(50).ToListAsync();
            return Results.Ok(new { item.Id, item.Name, item.OwnerId, item.IsClosed, members, events });
        });
        api.MapPost("/groups/{group:int}/{operation}", async (int group, string operation, HttpRequest http, HelperDb db, ClaimsPrincipal p, ChatGroupGate gate, IHubContext<MessengerHub> hub) =>
        {
            var me = await Messenger.UserAsync(db, p); await gate.Semaphore.WaitAsync();
            try
            {
                var membership = await Member(db, group, me.Id); var item = await db.ChatGroups.SingleAsync(g => g.Id == group); int? removed = null; string? detail = null;
                await using var transaction = await db.Database.BeginTransactionAsync();
                if (operation == "leave")
                {
                    if (item.OwnerId == me.Id) throw new ArgumentException("Передайте владение группой другому участнику или удалите группу перед выходом.");
                    db.ChatGroupMembers.Remove(membership); removed = me.Id;
                }
                else
                {
                    bool owner = item.OwnerId == me.Id;
                    if (!owner && !membership.IsAdmin) throw new UnauthorizedAccessException("Недостаточно прав для управления группой.");
                    if (operation is "close" or "delete" or "owner" or "admin" or "unadmin" && !owner) throw new UnauthorizedAccessException("Действие доступно только создателю группы.");
                    if (operation == "delete") { item.IsDeleted = true; item.IsClosed = true; }
                    else if (operation == "close") item.IsClosed = true;
                    else
                    {
                        if (item.IsClosed) throw new ArgumentException("Группа закрыта.");
                        if (operation == "rename") { var request = await http.ReadFromJsonAsync<GroupUpdate>() ?? throw new ArgumentException(); item.Name = Name(request.Name); detail = item.Name; }
                        else if (operation is "suspend" or "resume")
                        {
                            var request = await http.ReadFromJsonAsync<GroupSuspend>() ?? throw new ArgumentException();
                            var target = await db.ChatGroupMembers.SingleOrDefaultAsync(m => m.GroupId == group && m.UserId == request.UserId);
                            if (target == null || request.UserId == me.Id) throw new ArgumentException("Выберите другого участника.");
                            if (request.UserId == item.OwnerId || !owner && target.IsAdmin) throw new UnauthorizedAccessException("Нельзя управлять создателем или другим администратором группы.");
                            detail = (await db.Users.FindAsync(request.UserId))!.FullName;
                            if (operation == "suspend" && request.Minutes is < 1 or > 43200) throw new ArgumentException("Интервал: от 1 минуты до 30 дней.");
                            await db.ChatGroupRestrictions.Where(r => r.GroupId == group && r.UserId == request.UserId && r.EndsAt > DateTime.UtcNow).ExecuteUpdateAsync(s => s.SetProperty(r => r.EndsAt, DateTime.UtcNow));
                            if (operation == "suspend") db.ChatGroupRestrictions.Add(new() { GroupId = group, UserId = request.UserId, EndsAt = DateTime.UtcNow.AddMinutes(request.Minutes) });
                        }
                        else if (operation is "invite" or "remove" or "owner" or "admin" or "unadmin")
                        {
                            int id = (await http.ReadFromJsonAsync<GroupUser>() ?? throw new ArgumentException()).UserId;
                            var member = await db.ChatGroupMembers.SingleOrDefaultAsync(m => m.GroupId == group && m.UserId == id);
                            detail = (await db.Users.FindAsync(id))?.FullName;
                            if (operation == "invite")
                            {
                                if (!await db.Users.AnyAsync(u => u.Id == id && u.IsActive && u.PasswordHash == "!AD")) throw new ArgumentException("Участник недоступен.");
                                if (member == null)
                                {
                                    if (await db.ChatGroupMembers.CountAsync(m => m.GroupId == group) >= 100) throw new ArgumentException("Не больше 100 участников.");
                                    long maximum = await db.ChatGroupMessages.Where(m => m.GroupId == group).Select(m => (long?)m.Id).MaxAsync() ?? 0;
                                    var departure = await db.ChatGroupDepartures.FindAsync(group,id);
                                    if (departure == null) db.ChatGroupMembers.Add(new() { GroupId = group, UserId = id, JoinedAfterId = maximum, ReadThroughId = maximum });
                                    else
                                    {
                                        db.ChatGroupMembers.Add(new() { GroupId=group, UserId=id, JoinedAfterId=departure.JoinedAfterId, ReadThroughId=maximum, JoinedAt=departure.JoinedAt });
                                        db.ChatGroupRestrictions.Add(new() { GroupId=group, UserId=id, StartedAt=departure.LeftAt, EndsAt=DateTime.UtcNow });
                                        db.ChatGroupDepartures.Remove(departure);
                                    }
                                }
                            }
                            else
                            {
                                if (member == null || id == me.Id) throw new ArgumentException("Выберите другого участника.");
                                if (id == item.OwnerId || !owner && member.IsAdmin) throw new UnauthorizedAccessException("Нельзя управлять создателем или другим администратором группы.");
                                if (operation is "owner" or "admin") { await Member(db,group,id); if (!await db.Users.AnyAsync(u => u.Id == id && u.IsActive)) throw new ArgumentException("Участник отключён."); }
                                if (operation == "owner") { item.OwnerId = id; member.IsAdmin = false; membership.IsAdmin = false; }
                                else if (operation is "admin" or "unadmin") member.IsAdmin = operation == "admin";
                                else { db.ChatGroupMembers.Remove(member); removed = id; }
                            }
                        }
                        else throw new ArgumentException("Неизвестная операция.");
                    }
                }
                var labels = new Dictionary<string,string> { ["leave"]="вышел из группы", ["invite"]="пригласил", ["remove"]="исключил", ["suspend"]="временно отключил", ["resume"]="восстановил доступ", ["owner"]="передал владение", ["admin"]="назначил администратором", ["unadmin"]="снял права администратора", ["rename"]="изменил название", ["close"]="закрыл группу", ["delete"]="удалил группу" };
                if (removed != null)
                {
                    var oldMember = db.ChangeTracker.Entries<ChatGroupMember>().Single(e => e.Entity.GroupId==group && e.Entity.UserId==removed).Entity;
                    db.ChatGroupDepartures.Add(new() { GroupId=group, UserId=removed.Value, JoinedAfterId=oldMember.JoinedAfterId, ReadThroughId=oldMember.ReadThroughId, JoinedAt=oldMember.JoinedAt, LeftAt=DateTime.UtcNow });
                }
                long after = await db.ChatGroupMessages.Where(m => m.GroupId == group).Select(m => (long?)m.Id).MaxAsync() ?? 0;
                db.ChatGroupEvents.Add(new() { GroupId=group, AfterMessageId=after, Body=me.FullName + " · " + labels[operation] + (detail == null ? "" : " · " + detail) });
                await db.SaveChangesAsync(); await transaction.CommitAsync(); await Changed(db, group, hub, removed); return Results.Ok();
            }
            finally { gate.Semaphore.Release(); }
        });
    }
}
