using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Text;

namespace LitleHelperServer;

public class ChatMessage
{
    [System.ComponentModel.DataAnnotations.Schema.NotMapped] public string? SenderName { get; set; }
    [System.ComponentModel.DataAnnotations.Schema.NotMapped] public List<ChatFileInfo> Attachments { get; set; } = [];
    public long Id { get; set; }
    public int SenderId { get; set; }
    public int RecipientId { get; set; }
    public string Body { get; set; } = "";
    public string ClientId { get; set; } = "";
    public DateTime SentAt { get; set; } = DateTime.UtcNow;
    public DateTime? ReadAt { get; set; }
}
public record ChatSend(int RecipientId, string Body, string ClientId);
public class ChatPresence
{
    private readonly Dictionary<string, int> connections = new();
    private readonly Dictionary<string, Action> aborts = new();
    public void Add(string connection, int user, Action abort) { lock (connections) { connections[connection] = user; aborts[connection] = abort; } }
    public void Remove(string connection) { lock (connections) { connections.Remove(connection); aborts.Remove(connection); } }
    public void CloseAll() { Action[] actions; lock (connections) actions = aborts.Values.ToArray(); foreach (var abort in actions) abort(); }
    public bool Online(int user) { lock (connections) return connections.ContainsValue(user); }
}
[Authorize(AuthenticationSchemes = "Bearer")]
public class MessengerHub(HelperDb db, PanelSessions sessions, ChatPresence presence, MessengerSettings settings) : Hub
{
    public override async Task OnConnectedAsync()
    {
        if (!settings.Value.Enabled) throw new HubException("Мессенджер отключён администратором.");
        var user = await Messenger.UserAsync(db, Context.User!);
        sessions.Add(Context.ConnectionId, user.Id, Context.Abort);
        presence.Add(Context.ConnectionId, user.Id, Context.Abort);
        await Groups.AddToGroupAsync(Context.ConnectionId, "Chat:" + user.Id);
        await Clients.All.SendAsync("ChatChanged");
        await base.OnConnectedAsync();
    }
    public override async Task OnDisconnectedAsync(Exception? exception)
    {
        presence.Remove(Context.ConnectionId); sessions.Remove(Context.ConnectionId);
        await Clients.All.SendAsync("ChatChanged");
        await base.OnDisconnectedAsync(exception);
    }
}
public static class Messenger
{
    public static async Task<PanelUser> UserAsync(HelperDb db, ClaimsPrincipal principal)
    {
        var user = await db.Users.SingleOrDefaultAsync(u => u.Username == principal.Identity!.Name);
        if (user == null || !user.IsActive || user.AuthSource != "AD") throw new UnauthorizedAccessException("Для мессенджера войдите через AD.");
        return user;
    }
    public static async Task EnsureSchemaAsync(HelperDb db)
    {
        bool pg = db.Database.ProviderName!.Contains("Npgsql");
        if (pg) await db.Database.ExecuteSqlRawAsync("ALTER TABLE \"Users\" ADD COLUMN IF NOT EXISTS \"AdObjectId\" TEXT NOT NULL DEFAULT ''");
        else
        {
            var connection = db.Database.GetDbConnection(); bool open = connection.State == System.Data.ConnectionState.Open;
            if (!open) await connection.OpenAsync();
            using var command = connection.CreateCommand(); command.CommandText = "PRAGMA table_info('Users')";
            bool exists = false;
            using (var reader = await command.ExecuteReaderAsync()) while (await reader.ReadAsync()) if (reader.GetString(1) == "AdObjectId") exists = true;
            if (!exists) await db.Database.ExecuteSqlRawAsync("ALTER TABLE \"Users\" ADD COLUMN \"AdObjectId\" TEXT NOT NULL DEFAULT ''");
            if (!open) await connection.CloseAsync();
        }
        await db.Database.ExecuteSqlRawAsync("CREATE UNIQUE INDEX IF NOT EXISTS \"IX_Users_AdObjectId\" ON \"Users\" (\"AdObjectId\") WHERE \"AdObjectId\" <> ''");
        string id = pg ? "BIGINT GENERATED BY DEFAULT AS IDENTITY" : "INTEGER";
        string date = pg ? "timestamp with time zone" : "TEXT";
        string sql = $"CREATE TABLE IF NOT EXISTS \"ChatMessages\" (\"Id\" {id} PRIMARY KEY, \"SenderId\" INTEGER NOT NULL REFERENCES \"Users\"(\"Id\"), \"RecipientId\" INTEGER NOT NULL REFERENCES \"Users\"(\"Id\"), \"Body\" TEXT NOT NULL, \"ClientId\" TEXT NOT NULL, \"SentAt\" {date} NOT NULL, \"ReadAt\" {date} NULL)";
        await db.Database.ExecuteSqlRawAsync(sql); // Types above are fixed literals, never request data.
        await db.Database.ExecuteSqlRawAsync("CREATE UNIQUE INDEX IF NOT EXISTS \"IX_ChatMessages_SenderId_ClientId\" ON \"ChatMessages\" (\"SenderId\", \"ClientId\")");
        await db.Database.ExecuteSqlRawAsync("CREATE INDEX IF NOT EXISTS \"IX_ChatMessages_RecipientId_Id\" ON \"ChatMessages\" (\"RecipientId\", \"Id\")");
        await ChatFiles.EnsureSchemaAsync(db);
    }
    private static string Token(PanelUser user, IConfiguration config)
    {
        var claims = new[] { new Claim(ClaimTypes.NameIdentifier, user.Id.ToString()), new Claim(ClaimTypes.Name, user.Username), new Claim(ClaimTypes.Role, Roles.User), new Claim("version", user.SecurityVersion.ToString()), new Claim("messenger", "1") };
        return new JwtSecurityTokenHandler().WriteToken(new JwtSecurityToken(config["Jwt:Issuer"], config["Jwt:Audience"], claims, expires: DateTime.UtcNow.AddHours(8), signingCredentials: new SigningCredentials(new SymmetricSecurityKey(Encoding.UTF8.GetBytes(config["Jwt:SigningKey"]!)), SecurityAlgorithms.HmacSha256)));
    }
    public static async Task<PanelUser> ResolveAdUserAsync(AdIdentity identity, HelperDb db, CancellationToken cancellation)
    {
        var user = identity.ObjectId.Length == 0 ? null : await db.Users.SingleOrDefaultAsync(u => u.AdObjectId == identity.ObjectId, cancellation);
        user ??= await db.Users.SingleOrDefaultAsync(u => u.Username == identity.Username, cancellation);
        if (user != null && (user.AuthSource != "AD" || !user.IsActive || user.AdObjectId.Length > 0 && user.AdObjectId != identity.ObjectId)) throw new UnauthorizedAccessException("Учётная запись отключена или заменена в AD.");
        if (user == null)
        {
            user = new() { Username = identity.Username, FullName = identity.FullName, PasswordHash = "!AD", Role = Roles.User, AdObjectId = identity.ObjectId }; db.Users.Add(user);
            try { await db.SaveChangesAsync(cancellation); }
            catch (DbUpdateException)
            {
                db.Entry(user).State = EntityState.Detached;
                user = await db.Users.SingleOrDefaultAsync(u => u.Username == identity.Username, cancellation);
                if (user == null || !user.IsActive || user.AuthSource != "AD" || user.AdObjectId.Length > 0 && user.AdObjectId != identity.ObjectId) throw new UnauthorizedAccessException("Учётная запись недоступна.");
            }
        }
        if (user.Username != identity.Username && await db.Users.AnyAsync(u => u.Id != user.Id && u.Username == identity.Username, cancellation)) throw new UnauthorizedAccessException("Новое имя AD занято другой учётной записью в панели.");
        user.Username = identity.Username; user.FullName = identity.FullName; user.AdObjectId = identity.ObjectId;
        await db.SaveChangesAsync(cancellation); return user;
    }
    public static void MapMessenger(this WebApplication app)
    {
        app.MapGet("/api/messenger/windows", async (HttpContext http, IMessengerKerberos kerberos, IMessengerWindowsDirectory directory, HelperDb db, IConfiguration config, MessengerSettings settings, CancellationToken cancellation) =>
        {
            http.Response.Headers.CacheControl = "no-store";
            if (!http.Request.IsHttps) return Results.BadRequest(new { error = "Автовход доступен только через HTTPS." });
            if (!settings.Value.Enabled) return Results.Json(new { error = "Мессенджер отключён администратором." }, statusCode: 403);
            string header = http.Request.Headers.Authorization.ToString();
            IResult Challenge()
            { http.Response.Headers.WWWAuthenticate = "Negotiate"; return Results.Unauthorized(); }
            if (!header.StartsWith("Negotiate ", StringComparison.OrdinalIgnoreCase) || header.Length > 65536) return Challenge();
            KerberosIdentity verified;
            try { verified = kerberos.Authenticate(header[10..]); }
            catch (Exception ex) when (ex is System.Security.Authentication.AuthenticationException or FormatException or ArgumentException) { return Challenge(); }
            AdIdentity identity;
            PanelUser user;
            try { identity = await directory.FindAsync(verified.Name, cancellation); user = await ResolveAdUserAsync(identity, db, cancellation); }
            catch (UnauthorizedAccessException) { return Results.Json(new { error = "Учётная запись Windows отключена или недоступна в AD." }, statusCode: 403); }
            if (!string.IsNullOrEmpty(verified.ResponseToken)) http.Response.Headers.WWWAuthenticate = "Negotiate " + verified.ResponseToken;
            return Results.Ok(new { token = Token(user, config), user.Id, user.FullName });
        }).RequireRateLimiting("login");
        app.MapGet("/api/settings/messenger", async (MessengerSettings settings, HelperDb db) => new { settings.Value.Enabled, settings.Value.RetentionDays, storedMessages = await db.ChatMessages.CountAsync() + await db.ChatGroupMessages.CountAsync() }).RequireAuthorization("settings.manage");
        app.MapPut("/api/settings/messenger", (ChatOptions request, MessengerSettings settings, ChatPresence presence) =>
        {
            settings.Save(request);
            if (!request.Enabled) presence.CloseAll();
            return Results.Ok(settings.Value);
        }).RequireAuthorization("settings.manage");
        app.MapHub<MessengerHub>("/messengerHub", o => o.CloseOnAuthenticationExpiration = true);
        app.MapPost("/api/messenger/login", async (LoginRequest request, HttpRequest http, IAdAuthentication ad, HelperDb db, IConfiguration config, MessengerSettings settings, CancellationToken cancellation) =>
        {
            if (!settings.Value.Enabled) return Results.BadRequest(new { error = "Мессенджер отключён администратором." });
            if (!http.IsHttps && http.Headers["X-Forwarded-Proto"] != "https") return Results.BadRequest(new { error = "Вход в мессенджер доступен только через HTTPS." });
            AdIdentity identity;
            try { identity = await ad.AuthenticateAsync(request, cancellation); }
            catch (UnauthorizedAccessException) { return Results.Unauthorized(); }
            PanelUser user;
            try { user = await ResolveAdUserAsync(identity, db, cancellation); }
            catch (UnauthorizedAccessException) { return Results.Unauthorized(); }
            return Results.Ok(new { token = Token(user, config), user.Id, user.FullName });
        }).RequireRateLimiting("login");
        var api = app.MapGroup("/api/messenger").RequireAuthorization("Panel");
        ChatGroups.Map(api);
        ChatFiles.Map(api);
        api.AddEndpointFilter(async (context, next) => context.HttpContext.RequestServices.GetRequiredService<MessengerSettings>().Value.Enabled ? await next(context) : Results.Json(new { error = "Мессенджер отключён администратором." }, statusCode: 403));
        api.MapGet("/me", async (HelperDb db, ClaimsPrincipal p) => { var u = await UserAsync(db, p); return new { u.Id, u.FullName }; });
        api.MapGet("/users", async (HelperDb db, ClaimsPrincipal p, ChatPresence presence) =>
        {
            var me = await UserAsync(db, p);
            var users = await db.Users.AsNoTracking().Where(u => u.Id != me.Id && u.PasswordHash == "!AD" && (u.IsActive || db.ChatMessages.Any(m => m.SenderId == me.Id && m.RecipientId == u.Id || m.SenderId == u.Id && m.RecipientId == me.Id)))
                .OrderBy(u => u.FullName).Select(u => new { u.Id, u.FullName, u.Username, u.IsActive, branch = db.Branches.Where(b => b.Id == u.BranchId).Select(b => b.Name).FirstOrDefault(), unread = db.ChatMessages.Count(m => m.SenderId == u.Id && m.RecipientId == me.Id && m.ReadAt == null), lastId = db.ChatMessages.Where(m => m.SenderId == me.Id && m.RecipientId == u.Id || m.SenderId == u.Id && m.RecipientId == me.Id).Select(m => (long?)m.Id).Max(), lastAt = db.ChatMessages.Where(m => m.SenderId == me.Id && m.RecipientId == u.Id || m.SenderId == u.Id && m.RecipientId == me.Id).OrderByDescending(m => m.Id).Select(m => (DateTime?)m.SentAt).FirstOrDefault(), lastText = db.ChatMessages.Where(m => m.SenderId == me.Id && m.RecipientId == u.Id || m.SenderId == u.Id && m.RecipientId == me.Id).OrderByDescending(m => m.Id).Select(m => m.Body).FirstOrDefault() }).ToListAsync();
            return users.Select(u => new ChatListItem(u.Id, u.FullName, u.Username, u.IsActive, u.branch, u.unread, u.lastId, presence.Online(u.Id), u.lastAt, u.lastText)).Concat(await ChatGroups.ListAsync(db, me.Id));
        });
        api.MapGet("/history/{peer:int}", async (int peer, long? before, HelperDb db, ClaimsPrincipal p) =>
        {
            var me = await UserAsync(db, p);
            if (peer < 0) return await ChatGroups.HistoryAsync(ChatGroups.IdFromPeer(peer), before, db, me.Id);
            var rows = (await db.ChatMessages.AsNoTracking().Where(m => (m.SenderId == me.Id && m.RecipientId == peer || m.SenderId == peer && m.RecipientId == me.Id) && (before == null || m.Id < before)).OrderByDescending(m => m.Id).Take(50).ToListAsync()).OrderBy(m => m.Id).ToList();
            await ChatFiles.PopulateAsync(db, rows); return Results.Ok(rows);
        });
        api.MapPost("/send", async (ChatSend request, HelperDb db, ClaimsPrincipal p, IHubContext<MessengerHub> hub, ChatGroupGate gate) =>
        {
            var me = await UserAsync(db, p);
            if (request.RecipientId < 0) return await ChatGroups.SendAsync(request, db, me.Id, hub, gate);
            if (request.RecipientId == me.Id || !Guid.TryParse(request.ClientId, out _) || string.IsNullOrWhiteSpace(request.Body) || request.Body.Length > 4000 || request.Body.Any(c => char.IsControl(c) && c is not '\n' and not '\r' and not '\t')) throw new ArgumentException("Сообщение: от 1 до 4000 символов, выберите получателя.");
            var recipient = await db.Users.SingleOrDefaultAsync(u => u.Id == request.RecipientId && u.IsActive && u.PasswordHash == "!AD") ?? throw new ArgumentException("Получатель недоступен.");
            string clientId = Guid.Parse(request.ClientId).ToString("N");
            var message = await db.ChatMessages.SingleOrDefaultAsync(m => m.SenderId == me.Id && m.ClientId == clientId);
            if (message != null)
            {
                if (message.RecipientId != request.RecipientId || message.Body != request.Body.Trim()) throw new ArgumentException("Идентификатор сообщения уже использован.");
                return Results.Ok(message);
            }
            message = new() { SenderId = me.Id, RecipientId = recipient.Id, Body = request.Body.Trim(), ClientId = clientId };
            db.ChatMessages.Add(message);
            try { await db.SaveChangesAsync(); }
            catch (DbUpdateException)
            {
                db.Entry(message).State = EntityState.Detached;
                message = await db.ChatMessages.SingleOrDefaultAsync(m => m.SenderId == me.Id && m.ClientId == clientId);
                if (message == null) throw;
                if (message.RecipientId != request.RecipientId || message.Body != request.Body.Trim()) throw new ArgumentException("Идентификатор сообщения уже использован.");
                return Results.Ok(message);
            }
            await hub.Clients.Groups("Chat:" + recipient.Id, "Chat:" + me.Id).SendAsync("ChatMessage", message);
            return Results.Ok(message);
        });
        api.MapPost("/read/{peer:int}/{through:long}", async (int peer, long through, HelperDb db, ClaimsPrincipal p, IHubContext<MessengerHub> hub) =>
        {
            var me = await UserAsync(db, p);
            if (peer < 0) return await ChatGroups.ReadAsync(ChatGroups.IdFromPeer(peer), through, db, me.Id, hub);
            await db.ChatMessages.Where(m => m.SenderId == peer && m.RecipientId == me.Id && m.Id <= through && m.ReadAt == null).ExecuteUpdateAsync(s => s.SetProperty(m => m.ReadAt, DateTime.UtcNow));
            await hub.Clients.Groups("Chat:" + peer, "Chat:" + me.Id).SendAsync("ChatChanged"); return Results.Ok();
        });
    }
}
