[libdefaults]
    default_realm = GP1.LOC
    dns_lookup_kdc = true
    dns_lookup_realm = false
    rdns = false

[realms]
    GP1.LOC = {
        kdc = dc01.gp1.loc
    }

[domain_realm]
    .gp1.loc = GP1.LOC
    gp1.loc = GP1.LOC
